#!/usr/bin/env python3

import math
import sys
import os
from direction import *

def open_txt(sys):
    if (len(sys.argv) > 1):
        try :
            f = open(sys.argv[1], "r")
        except :
            sys.stderr.write("This file doesn't exist or can't be open\n")
            sys.exit(84)
    else :
        try :
            f = open("file.txt", "r")
        except :
            sys.stderr.write("Enter in argument the name of your file\n")
            sys.exit(84)
    return (f)

def get_args(args, f):
    for line in f:
        for word in line.split():
            args.append(word)
    return (args)

def move(x, y, dir, x_max_floor, y_max_floor):
    if (dir == 1):
        y += 1
        if (y > y_max_floor):
            sys.stderr.write("The automatic vacuum cleaner is out of the floor range\n")
            sys.exit(84)
        return (x, y)
    if (dir == 2):
        x += 1
        if (x > x_max_floor):
            sys.stderr.write("The automatic vacuum cleaner is out of the floor range\n")
            sys.exit(84)
        return (x, y)
    if (dir == 3):
        y -= 1
        if (y < 0):
            sys.stderr.write("The automatic vacuum cleaner is out of the floor range\n")
            sys.exit(84)
        return (x, y)
    if (dir == 4):
        x -= 1
        if (x < 0):
            sys.stderr.write("The automatic vacuum cleaner is out of the floor range\n")
            sys.exit(84)
        return (x, y)
    return (x, y)


def execute_actions(x_max_floor, y_max_floor, x, y, dir, actions):

    for i in range(len(actions)):
        if (actions[i] == "D" or actions[i] == "G"):
            dir = update_direction(dir, actions[i])
        elif (actions[i] == "A"):
            x, y = move(x, y, dir, x_max_floor, y_max_floor)
    return (x, y, dir)

def help():
    print("USAGE :\n\t./vacuum <file text>\nGOAL :\n\tObtain the final position of the automatic vacuum\n\tafter multiple actions")
    sys.exit(0)

def main():
    if (len(sys.argv) == 1):
        sys.stderr.write("Error: Please enter argument.\nIf you need help, write ./vacuum -h\n")
        sys.exit(84)
    if (sys.argv[1] == "-h"):
        help()
    args = []
    f = open_txt(sys)
    args = get_args(args, f)
    try :
        x_max_floor = int(args[0])
        y_max_floor = int(args[1])
        x = int(args[2])
        y = int(args[3])
        dir = args[4]
        actions = args[5]
    except :
        sys.stderr.write("Not good arguments in the file")
        f.close()
        sys.exit(84)
    dir = set_direction(dir)
    x, y, dir = execute_actions(x_max_floor, y_max_floor, x, y, dir, actions)
    dir = get_direction(dir)
    print(x, y, dir)
    f.close()

main()